requirements.txt
Simply just some hygiene, locking down the dependencies will help prevent weird bugs that will pop up for new contributors.
=> Locking down the dependencies versions

README.md
1. I don't really think it matters whether the PR author makes a branch in this repo (where they may not have permissions), or whether they do it in their own fork (which is a more standard open source practice).
2. Opinions differ on this point, but I don't really like squash merges. They obscure credit for work, and they can overwrite semantically useful content in how the commits are split up.
=> Suggestions for changes to PR procedure

public/index.html
this PR completes the temporary removal of the 'endangered' palette and view from the drop down menu
#73
=> remove Endangered from dropdown

public/js/Palettes.js
we might take out the diameter palette, and this set of colors don't work, but the 7-12 inch points were never meant to be shaded white. I just want to correct that.
=> fix 7 inch diamater color

public/index.html
this PR removes the term "nativity" from the sidebar and takes that data out of the table view into the header (it now appears above the table)
=> reformat native data in sidebar

public/index.html
this PR removes the term "nativity" from the sidebar and moves that data out of the table view into the header (it now appears above the data table)
=> move native field out of table

public/css/main.css, public/js/Map.js
What I did:
- disable default zoomControl to change default settings
- add a zoomControl with 'bottomleft' position (puts zoom in/out buttons nicely into the Pacific Ocean)
- remove CSS that was hiding the default zoomControl (probably because it was in upper left and bumping into the filters)
=> add map zoom in/out button #106

public/js/Map.js
to use the leaflet function setView, this PR renames this.map to this.leafletMap throught the map.js file, in order to differentiate between leaflet's "map.whateverfunction" and "map" as defined in the file
this PR uses the setView function to re-position the visible map. the map will now zoom in and center on the user's selected marker. because the sidebar occupies a big chunk of the screen, we adjusted the longitude setView uses as its center (called newViewLocation) so that the marker appears closer to the center of the visible map
fixes #118
=> add setView

public/js/Map.js
this PR lowers each circleMarker's fillOpacity to 0.75 in map.js
fixes #122
=> reduce fillOpacity to 0.75

public/js/Map.js
#120   remove close button from tree name popup
official docs checked. closeButton found, it's a boolean, so declaring it to false it's enough to solve that issue.
=> Issue #120 fixed

public/js/Map.js
If after we zoom in for them, the user has increased or decreased the zoom level by one, don't re-zoom on them. They probably like their current zoom level. At least this is a preference I've found that I have, and thought I'd offer this tweak. Take it or leave it, no problem either way!
=> Only zoom in if we're zoomed out.

public/js/SpeciesFilter.js
this PR removes the line of code that excluded vacant sites from the select2 dropdown. other types of vacant sites (asphalted well, stump, etc) are already included as options in the select2 list
fixes #131
=> adds "vacant site" to select2 dropdown menu

public/index.html
even though the URL is temporary (and this script won't work if someone looks at the github pages version), I think it makes sense to see if people visit the current site (other than Brenda)
=> add google analytics for surge.sh

public/js/Geolocation.js
fixes #153 
the issue described in #153 is actually due to a block on location services in the mobile browser. this PR adds a pop-up error message so that a user will know whether or location services are enabled
=> add error message if browser does not enable location services

public/js/main.js
When a user loads the map to a specific point (eg [this tree](https://public-tree-map.surge.sh/?id=10936680)), it's easier for the user to understand the map if the markers are automatically colored by species or family.
| before |
|---|
|![Screen Shot 2019-08-30 at 3 43 50 PM](https://user-images.githubusercontent.com/22624609/64054806-9bde6e00-cb3d-11e9-8953-af9cc89f539a.png)
| after |
|---|
|![Screen Shot 2019-08-30 at 3 44 02 PM](https://user-images.githubusercontent.com/22624609/64054795-8c5f2500-cb3d-11e9-80c3-2dfefa72998d.png)
changed default view in main.js to 'name_common'
=> switch default view (for now) to species

public/index.html
hides water needs, shade, and invasive options from color filter
after some conversations with the city urban forest staff and Poliana Raymer at SMC, it seems like we need to be more detailed with visually representing water and shade (eg consider tree height and diamater). we also decided to try combining the invasive and CA native views (the data aren't yet reformatted). Jess suggests that fewer options will translate better into a button-type filter bar
| before | 
|---|
|  | 
| after |
|---|
|  |
-  I deleted the lines for water needs, shade, and invasive options from the color filter in index.html file
=> limit color filter

public/js/Palettes.js, public/js/Sidebar.js
resolves #171 
-  this PR updates the "CA native" palette to include plants designated as invasive/watch by cal ipc. I haven't updated the colors in the CA native palette, I just included the relevant cal ipc fields and used the existing colors. 
- colors will need an update (see #150)
| before |
|---|
|  
| after |
|---|
|![Screen Shot 2019-08-30 at 9 27 01 PM](https://user-images.githubusercontent.com/22624609/64059272-eaa3fc00-cb6d-11e9-8a6a-af649bdcb6ef.png)|
- I moved the moved the "invasive" palette into the "CA native" palette 
- I updated the conditions in sidebar.js so that the cal-ipc designated species are identified in the relevant info panels as exotic (not native to california) rather than "unknown"
=> update native/invasive palette, sidebar text

public/css/main.css
adjust sidebar image credit to (at least somewhat) match zeplin
the image credit in the infopanel in zeplin is on the opposite side
| before | 
|---|
|  | 
| after |
|---|
|  |
- 
I switched the image credit from L to R and added some formatting
=> move image credit

public/css/main.css, public/index.html
addresses #200 
this pr adjusts the heights and font sizes for the two search bars (for desktop users)
|---|---|
| ![Screen Shot 2019-09-26 at 8 41 42 PM](https://user-images.githubusercontent.com/22624609/65740575-1a2b2300-e09e-11e9-8364-70c12adac275.png) | ![Screen Shot 2019-09-26 at 8 33 41 PM](https://user-images.githubusercontent.com/22624609/65740524-ec45de80-e09d-11e9-9924-ba01665b1e63.png)
|
- 
- narrowed the width of the algolia address search bar (temporarily, to accommodate larger text size in the buttons)
- made the search bars uniform height
- made the text across the toolbar a uniform size
=> adjust toolbar formatting

public/css/main.css, public/index.html
make sidebar narrower #202
addresses #
the sidebar takes up a lot of room on the website, limits how much map a user can see. 
|---|---|
| ![Screen Shot 2019-10-06 at 1 12 17 PM](https://user-images.githubusercontent.com/22624609/66275189-11271800-e83b-11e9-8985-77e7de1ca632.png) | ![Screen Shot 2019-10-06 at 1 25 13 PM](https://user-images.githubusercontent.com/22624609/66275370-cefed600-e83c-11e9-8204-318d8f0fdb95.png)|
-  narrows sidebar 
-  adjusts banner text and image formatting to look more like the zeplin mockup
=> set sidebar to be 25% width of window

public/css/main.css, public/js/ColorFilter.js, public/js/Legend.js, public/js/Map.js, public/js/SpeciesFilter.js, public/js/main.js
addresses #172 
<table>
<tr>
<td>before</td><td>after</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
- color keys on select2 options/selections
- change color keys to match markers when changing group color filter (excluding unused heritage button)
Also I just noticed there are white color keys when grouping by endangered. Will the color scheme for the select2 need to be tweaked? Or will it be made redundant later?
=> color keys for select2 options/selections

public/index.html, public/js/Map.js, public/js/Palettes.js, public/js/SpeciesFilter.js
resolves #208 
- heritage group filter emphasizes heritage markers (you can tweak color and size in the palette to what you consider appropriate)
- select2 color keys and off-screen auto zoom works with heritage group filter
- not sure if this one is necessary (5286d2c) but I removed non-heritage tree markers when filtering species with heritage group filter (although they would have been white anyway). Depends on the context of the use case? Don't merge da0ad28 if you're not merging 5286d2c.
=> Heritage group filter

public/css/main.css, public/index.html
The buttons are now wrapped in divs, and once you call for a button within the div they worked again.
Afterwards I refactored some of the repetitive code into a separate class so that there was no more unnecessary overlap.
=> Added the previous classes back to the buttons

public/js/Map.js
Let's see if this works on a real mobile device
Adds mobile "touch" event in addition to the mouse "click" event to open the tree data
addresses #52
=> Touch markers

public/js/Map.js
from @theswerd:
"If this doesn't work idk
This time on touch devices it will register for clicks and for mouseovers, but on non touch devices it will just register for clicks."
addresses #52
=> revised touch marker

public/js/Map.js
When ensuring a filtered marker is in view, it is sometimes hidden under the toolbar
- when the closest marker is above (visually) a specified y-coordinate threshold, padding is added
current threshold set (if the marker was a single pixel higher the view would zoom out more to include the section above where it is now):
=> bugfix filtered marker under toolbar

public/js/Map.js
highlighted marker becomes normal when select2 filter is used
- reassigned highlighted marker during redraw based on tree ID
- onZoomChanged got renamed to look natural being used elsewhere
=> retain highlighted marker when filtered

public/js/main.js
resolves #256 
right now, the warning is out of sync for iphone users (it appears when the user is viewing the site in portrait, not landscape). as a result, the pop up warning to switch the phone's orientation is annoying to users (more so it seems than is the site's imperfect appearance in landscape view)
- remove mobile window orientation detection and the pop up warning
=> Hide orientation warning

public/css/main/toolbar.css, public/css/mobile/toolbar.css, public/index.html
Fixes borders and background colors of toolbar buttons.
resolves #247
|---|---|
| See #247 | ![image](https://user-images.githubusercontent.com/46986917/71864614-1bb0b200-30b5-11ea-8e5f-507ef1318623.png) |
I changed a little bit of the css so the borders would apply to each buttons instead of the group of buttons as a whole.
=> fix mobile toolbar button display

public/css/mobile/sidebar.css, public/index.html, public/js/Sidebar.js
resolves #201
updates formatting for vacant site sidebars in mobile and desktop views.
before:
mobile:
desktop:
after:
mobile:
desktop:
- match formatting for 5 vacant categories in sidebar.css and index.html
=> Vacant formatting

public/js/Map.js
resolves #225
|![Screen Shot 2020-04-23 at 12 13 46 AM](https://user-images.githubusercontent.com/24775373/80070554-f88cff80-84f7-11ea-8eec-1f30e4ab2f3c.png)|
|
this problem is caused by the default minWidth setting of Leaflet popUp. Overriding the default setting to 0 fixes the problem.
=> fix mobile popup display

public/css/main/toolbar.css, public/js/Map.js
resolves #278 
Hardcoding the map bounds fixed the issue. Tested on iOS. 
**iOS Debug Notes:**
Fought with this for quite a bit, best way I think is to use Safari Web Inspector following [these instructions](https://medium.com/better-programming/debugging-your-iphone-mobile-web-app-using-safari-development-tools-71240657c487).
Additionally, Safari does not allow location service over HTTP. In order to debug and test on iOS, the website must be served over HTTPS. Follow these steps if using live server with vs code:
- create private key and certificate
openssl genrsa -aes256 -out localhost.key 2048   
openssl req -days 3650 -new -newkey rsa:2048 -key localhost.key -x509 -out localhost.pem
- create `.vscode/settings.json` in project folder, add following:
{
"liveServer.settings.https": { …
=> fix bounds

public/js/Sidebar.js
Fixed [this](https://github.com/Public-Tree-Map/public-tree-map-data-pipeline/issues/63) in the data repo.
Pretty much just an array indexing problem. 
(Side effect: the default image for every single tree is now a different one)
before
after
=> fix sidebar image display

public/css/mobile/toolbar.css, public/index.html
**temporary fix**
On the current mobile site, only two view options are available (species and family). Since the heritage tree program's a city public landscape priority, I'm switching the family button to a heritage button. In the future, it'd be great to give mobile users access to more than two views (it's on the list of design questions)
related:
I also think it might make sense to change "GROUP BY" to "VIEW BY"
If non heritage trees are fully hidden in heritage view (rather than just given white markers), would user experience improve?
|---|---|
| ![Screen Shot 2020-05-24 at 1 22 49 PM](https://user-images.githubusercontent.com/22624609/82764178-c0f8c800-9dc1-11ea-9f58-0737d3d9e4de.png) | ![Screen Shot 2020-05-24 at 1 23 10 …
=> update mobile toolbar

public/css/master.css, public/css/mobile/map.css, public/css/mobile/toolbar.css, public/index.html, public/js/Map.js
addresses #296 
Mobile view now shows species search and locate button, hides address bar
=> Mobile species filter

public/css/mobile/toolbar.css, public/index.html, public/js/Palettes.js
addresses #150 
I'd like to use the mobile button toggle to allow users to find the limited number of public trees native to CA floristic province
(testing as iphoneX - issue with white bottom border documented in #245)
before:
after:
- switch the mobile toggle from species / SM heritage to species / native
- update native color palette (to try to improve legibility) - color blind safe according to colorbrewer
=> CA native mobile button

.github/workflows/gh-pages.yml
This GitHub Action runs on a push to `master`. The contents of the `public/` folder, as well as the `CNAME` file, are copied to the `gh-pages` branch.
Resolves #297 
*Note*: The action will create the `gh-pages` branch if it does not already exist.
=> GitHub Action to deploy site to gh-pages
