Public-Tree-Map/public-tree-map

src/App.js
src/Leaflet.css
src/NavContainer.js
src/statsContainer.js

produced locally in a different file and added to stm. Used React/Grid package styled-components. This is only the right nav bar from the pdf's top page.

React NavBar to be reviewed

---

package.json
src/App.js
src/Leaflet.css
src/NavContainer.css
src/NavContainer.js
src/StatsContainer.css
src/statsContainer.js

- removed bootstrap
- moved css to fies
- reproduced navContainer and Stats Container with Foundation

Frontend Framework Restructuring

---

.gitignore
.npmrc
README.md
yarn.lock

Commit a yarn lockfile and update the README to use yarn.
Follow up to #45 (@ian-r-rose)

Choose yarn.

---

public/index.html
public/js/Palettes.js

Added dropdown options and palettes for the following tree properties:
<option value="family_name_botanical">Family</option>
<option value="irrigation_requirements">Water Needs</option>
<option value="shade_production">Shade</option>
<option value="iucn_status">Endangered</option>
<option value="height_min_ft">Height</option>
<option value="diameter_min_in">Diameter</option>

add new palettes

---

public/js/Palettes.js

this PR changes the drop down menu option from 'nativity' to 'CA native'

native color palette update

---

public/index.html

Removed form field from index.html from the sidebar @emillipede #78

removed form field

---

public/js/Sidebar.js

remove additional reference to 'form' from sidebar

remove 'form' attribute from sidebar

---

public/css/main.css
public/index.html
public/js/Map.js
public/js/SpeciesFilter.js
public/js/main.js

This adds a dropdown for filtering by species.

Species filter

---

public/js/Map.js

this PR zooms out the default map view a little bit to fit in more of the tree points and show some of the city boundaries

zoom out map

---

public/js/Map.js

updated center point moves more of the ocean out of the default view

adjust map center point

---

public/js/Map.js

Missed a spot where we need to update the palette state.

---

public/index.html

this PR removes the visible but not functional address search bar from index.html 
addresses issue #89

remove (inactive) address search bar from UI

---

public/js/Map.js

@ian-r-rose thought the last iteration looked off center, I think I agree

move center point NE

---

public/index.html

this PR adds un-styled placeholder text (replacing "tree stuff")

update homepage placeholder text

---

public/js/Sidebar.js

Also need to update/remove "Nativity" from the sidebar

update CA native descriptive text

---

public/index.html

Reverts Public-Tree-Map/public-tree-map#111
I will merge this PR directly into master. It doesn't belong on the 'family-name-common' branch

Revert "reformat native data in sidebar"

---

public/index.html
public/js/Sidebar.js

also add parts of the "nearest address" lookup

Add common family name to sidebar.

---

public/js/Map.js

- Store marker's value and revert its radius when another one is clicked
- Re-enlarge it after zooming events
- Renamed e to leafletEvent, as e can stand for event or error, so to clarify
- Created a new function for enlarge/shrinking the radius, changeCircleMarker
- TODO (possibly): Revert the enlarged radius after some other events?

Double the radius of a tree's marker when you click on it

---

public/index.html
public/js/Map.js

This is a stab at adding a color ring around the selected marker. I chose to use library called Colors to darken the current color. Feel free to ditch that and use, say, a dark grey instead. And you @emillipede  closed issued 121 already, so feel free to ignore this PR completely!

Highlight selected circlemarker 121

---

public/js/Map.js

in this PR, I've added a line that allows for the selected circleMarker to be visible in areas that include a lot of trees and overlapping markers
fixes #133

bringToFront selected circleMarker

---

public/index.html

- Also use Subresource Integrity (SRI) from their CDNs

Update Leaflet and jQuery to latest versions

---

public/index.html
public/js/Palettes.js

Fixes #97.
- Used the 3 colors from design mockup

Add Invasive map view

---

public/css/main.css

Added Padding to the default sidebar

Default Sidebar Padding

---

public/css/main.css
public/index.html
public/js/Sidebar.js

Add panel for vacancies with some placeholder text.

---

public/js/Sidebar.js

Tree id 10914829 is an example of the issue.  If searching manually on the map, located at 14th and Rose Ave.

Sidebar should properly display information

---

public/index.html
public/js/Geolocation.js
public/js/main.js

Autocomplete address search and zoom to my location via Algolia Places

---

public/index.html
public/js/Map.js
public/js/Sidebar.js

Uses the URLSearchParams interface to get the query parameters from the address bar in map.js. It checks to see if the address bar has the parameter "id" and uses that value to get the information for the tree with that id to display in the sidebar.
Still want to update the query parameters in the address bar dynamically when the user clicks on a different tree.

Added code for parsing URL for tree id query parameter

---

public/js/Map.js
public/js/Sidebar.js

Fix a few errant tabs.

---

public/css/main.css
public/js/Sidebar.js

adds scrolling to the vacant sidebar panel
fixes #146

vacant-sidebar-overflow

---

public/index.html
public/js/Sidebar.js

this update add rules so that the species without cal IPC ratings now appear as "not listed"
@thekaveman helped me make this update work, told me to add the triple equals and the ipcRating
fixes #160

fix cal-ipc formatting

---

public/css/main.css

Now the whole thing is scrollable, rather than having the image pinned

This unpins the image

---

public/css/main.css
public/index.html

add link to data sources github

---

public/index.html

defaults to "species" in dropdown

---

public/css/main.css
public/index.html
public/js/Sidebar.js

resolves #79
This is a slider to allow users to school through the images
Original:
New:

Slider Working!

---

public/js/Map.js

resolves  #179 
- Look for the selected marker closest to the center of the current view
- Extends the view to encompass it

include at least one filtered marker in view

---

public/css/main.css
public/index.html
public/js/ColorFilter.js
public/js/SpeciesFilter.js

resolves #
addresses #
|---|---|
| <img width="997" alt="Screen Shot 2019-09-17 at 11 20 32 PM" src="https://user-images.githubusercontent.com/15054682/65119975-cafc3880-d9a1-11e9-9962-e7d4db2b2b23.png"> | <img width="997" alt="Screen Shot 2019-09-17 at 11 17 02 PM" src="https://user-images.githubusercontent.com/15054682/65119702-63de8400-d9a1-11e9-8857-abfcf42df149.png"> |
-

redesigned toolbar based upon zeplin

---

public/css/main.css
public/index.html

resolves #200 
addresses #
|---|---|
|  |  |
-

fixed height of select2 and color filter buttons

---

public/css/main.css

reset button font to 14 (to match zeplin) - other toolbar/button changes require more work to resolve

increase toolbar button font size

---

public/js/Sidebar.js

In creating the mobile view we deleted one of the close methods.
This branch puts it back

Working close button

---

public/css/main.css
public/js/Map.js

update hover formatting to match zeplin 
resolves #198
addresses #
| current hover | zeplin hover |
|---|---|
|![Screen Shot 2019-09-23 at 10 34 44 PM](https://user-images.githubusercontent.com/22624609/65484136-4f900080-de53-11e9-8012-a1236d77b0f8.png)|![Screen Shot 2019-09-23 at 10 34 54 PM](https://user-images.githubusercontent.com/22624609/65484140-528af100-de53-11e9-9295-8b6649c03ef5.png)| 
|PR hover |
|---|
|![Screen Shot 2019-10-22 at 4 38 03 PM](https://user-images.githubusercontent.com/22624609/67343543-6c6b3280-f4ea-11e9-8e15-25628223c913.png)|
-

redesigned popup on hover

---

public/js/Map.js

Uses if statement
(revision of previous PR)
addresses #52

Touch markers v2

---

public/js/Map.js

Uses if statement to check for hovering on press if on mobile
addresses #223

Touch Markers v3

---

public/css/main.css

resolves #221 
addresses #
|---|---|
|  |  |
-

increased z-index

---

public/css/mobile.css

addresses #227
|---|---|
|  |  |
-

fixed toolbar spacing

---

public/js/Sidebar.js

Added touch start and touch move methods

---

public/js/main.js

resolves #
addresses #
|---|---|
|  |  |
Not sure if this code to lock the phone will actually work:
screen.orientation.lock("portrait-primary");
But at least it can detect the orientation and issue an alert to ask the user to rotate their phone back to portrait mode.

added window orientation

---

public/js/Sidebar.js
public/js/main.js

Hides sidebar on touch devices

---

public/js/Sidebar.js

For you to call index[1], and guarentee it doesn't through an error, you need to make sure the image list has atleast to items
resolves #249

Fixed Error #249

---

public/css/main/sidebar.css
public/css/mobile/sidebar.css
public/index.html
public/js/Sidebar.js

resolves #190 
addresses #
|---|---|
|  |  |
Added heritage tree information when a heritage tree is selected.

finished adding heritage to sidebar

---

public/css/main/toolbar.css
public/index.html
public/js/Map.js

resolves #255 
Need a way for the user to be able to see in real time where their location is on the tree map. Helps user see which trees are near them.
|---|---|
|![image](https://user-images.githubusercontent.com/46986917/77983520-16ce5980-72c4-11ea-8c3f-62c4ee6e5417.png)|![image](https://user-images.githubusercontent.com/46986917/77983413-da9af900-72c3-11ea-9ed1-923395824bb9.png)|
Add a button that when clicked on, zoom's to the user's location causes a blue indicator to appear there. the indicator will change as the user's location changes.

Location indicator

---

public/css/main/sidebar.css
public/index.html
public/js/Sidebar.js

resolves #257 
seem like a quick enough piece to knock out
- add a div to bottom of sidebar in index.html, and corresponding css in sidebar.css
- add function fillLastUpdate() to Sidebar.js, called in Sidebar.showDefault() to update info
- within fillLastUpdate(): google cloud storage api was called, and returned xml was parsed to fill in the last updated date

create sidebar bottom div with latest update date

---

public/css/main/sidebar.css

|---|---|
|  ![Screen Shot 2020-04-25 at 8 31 05 AM](https://user-images.githubusercontent.com/22624609/80283785-398b3c80-86cf-11ea-9904-4fc52b319a59.png) |  ![Screen Shot 2020-04-25 at 8 31 35 AM](https://user-images.githubusercontent.com/22624609/80283797-46a82b80-86cf-11ea-90eb-1294490033cb.png)|
- italicized text
- changed em values to px

italicize last checked date

---

README.md
ROADMAP.md

addresses #267 
- update readme 
- - adds link to the current slack channel and information about basic setup

Onboarding docs

---

README.md

-  update readme links to slack workspace

update slack links

---

public/index.html

addresses #63 
current look
link opens the work form in a new tab

report issue section in sidebar-tree

---

public/js/Map.js

resolves #272 
selected marker now display correctly upon view change
- removed the code causing the problem

marker size fix

---

public/js/Sidebar.js

- use constant for default position
- initilize scroll variable
- added comments
Images should now scroll normally without skipping

fix image scrolling

---

public/index.html

addresses #176 
temporary (non designed) update to index.html to make "about" and "feedback" links active. added instagram link. all links open in new tabs. this PR includes the links at the bottom of each sidebar. needs design help.
- add links to index.html

add "about" and "feedback" link

---

.github/issue_template.md
public/index.html

after adding new issue templates, I updated the sidebar "feedback" links to take users to the new issue template page and I updated the previous issue template

update site links to submit new issues

---

public/css/main/map.css
public/css/main/toolbar.css
public/js/Geolocation.js
public/js/Map.js

Implements update proposed [here](https://github.com/Public-Tree-Map/public-tree-map/issues/278#issuecomment-632276298)
Address bar now drops a pin at target location.
Map panning from one location to another is a bit off, might look into later. Current state seem publishable? @emillipede

Address bar update

---

public/js/Map.js

this PR changes the text in the location permission message. I want to make sure users understand that we respect their privacy and don't track/store gps data

update permission message

---

public/js/Geolocation.js

fix problem mentioned [here](https://github.com/Public-Tree-Map/public-tree-map/pull/285#issuecomment-632703658)
- use leaflet.flyTo for smooth transition and centered target location
- remove redundant code

fix address bar panning animation

---

public/css/main/sidebar.css
public/css/mobile/sidebar.css
public/index.html
public/js/Sidebar.js

- hide scrolling arrows
- swipe left : next image
- swipe right: prev image
- remove redundant code

setup sidebar image area touch functions for mobile with hammer.js

---

public/index.html
public/js/Sidebar.js

addresses #281 
simple hack: link in sidebar, open up streetview at tree location in a new window/tab
alternatively, we can do a overlay displaying streetview image on top of the current map (as proposed in the issue), but this would involve :
- an API key
- potential terms of service violation
- a lot more code
so maybe slate this for if and when necessary?

add simple google streetview

---

public/js/Sidebar.js
public/js/main.js

fixing up the mess I made in #268 
switch to extracting info from existing json call to :
-reduce load time
-reduce code clutter

refactor "last updated" section in sidebar

---

public/css/mobile/toolbar.css

resolves #245 
addresses #296 
improves on #298 
- actually sat down and dug into CSS documentations
- preformed CSS jiujitsu

Mobile species filter

---

public/css/mobile/toolbar.css

fix [this](https://github.com/Public-Tree-Map/public-tree-map/issues/296#issuecomment-643663915)
tested on iPhones

fix input field auto focus zooming on mobile

---

public/css/mobile/main.css
public/css/mobile/map.css
public/css/mobile/sidebar.css
public/css/mobile/toolbar.css
public/js/Sidebar.js
public/js/main.js

resolves #245 
got rid of weird white spaces with CSS adjustments

Mobile view fix

---

public/index.html

resolves #204 
- Add a link in the sidebar to the google form @emillipede created

Add link to hertiage nomination google form in sidebar

---

README.md

addresses #301 
the readme didn't reflect that we're working to add data for other cities. I added that clarification.

Update readme la trees

---

README.md

Friends of the Urban Forest, a non profit organization in SF, is an interesting model of local government / non profit collaboration to plant public trees. They also run educational programs and foster community engagement with the city's urban forest
- add FUF (fuf.net) to the readme's list of related projects and sources of inspiration

add FUF to readme

---

README.md

resolves #
addresses #316 
|---|---|
|  |  |
-

add documentation about new milestone
